## 基础 Python 介绍

- 资料型态
- 逻辑判断
- 回圈
- 范例：画个圣诞树
- 范例：猜数字游戏
- 小练习：读唐诗 数数字

In [1]:
## 常用的基本型态

a = 123
print('变量 a 的型态是：', type(a))

b = 10.0
print('变量 b 的型态是：', type(b))


first_string = 'Hello World'
print('变量 first_string 的型态是：', type(first_string))

flag = True
print('变量 flag 的型态是：', type(flag))

变量 a 的型态是： <class 'int'>
变量 b 的型态是： <class 'float'>
变量 first_string 的型态是： <class 'str'>
变量 flag 的型态是： <class 'bool'>


In [2]:
## 数字的相加

a = 2
b = 5
print(a + b)


## 字符串的相加

c = 'Hello'
d = 'World'

print(c + d)

7
HelloWorld


In [3]:
print('a 乘上 b: ', a * b)
print('a 除以 b: ', a / b)
print('b 除以 a 的余数: ', b % a)
print('a 的 b 次方: ', a ** b)
print('a 的 b 次方: ', a ** 0.5)

a 乘上 b:  10
a 除以 b:  0.4
b 除以 a 的余数:  1
a 的 b 次方:  32
a 的 b 次方:  1.4142135623730951


In [ ]:
## 猜猜看会发生什么事？


a + c

## 逻辑判断式

 > 还记得课堂上提到过，`rule base` 是机器学习的起手式吗？
 
 
**来看看一个 `rule base` 的投资理财推荐服务**

In [ ]:
# 多功能 if 、 else if 、 else 判斷

deposit = int(input("请输入你的存款："))

if deposit < 10000:
    print("孩子，先努力再多存点吧！")
    
elif deposit >= 10000 and deposit <= 50000:
    print("可以开始尝试点零股投资")

elif deposit > 50000 and deposit < 100000:
    print("可以考虑开始买股，但如果稳健些可以再多存点")

elif deposit >= 100000:
    print("你可以直接买股了！")
        
else:
     print("例外处理")

## 回圈：循序的把事情完成


* 举例来说，把 100 以内的数字做加总

```
total = 0

for i in range(0, 100):
    total = total + i
```

* 也可以用 while
 
```
total = 0
i = 0

while i < 100:
    total = total + i
    i += 1
```

**来看看一个 `计算每个人BMI值` 的健康数值计算机**

In [4]:
height = [166, 178, 152, 165, 187, 140]
weight = [62, 65, 50, 58, 82, 45]

for i, j in zip(height, weight):
    bmi = j / (i/100)**2
    print(f'这位同学的身高是：{i}，体重是：{j}。所以BMI值就是：{bmi}')

这位同学的身高是：166，体重是：62。所以BMI值就是：22.49963710262738
这位同学的身高是：178，体重是：65。所以BMI值就是：20.515086478979924
这位同学的身高是：152，体重是：50。所以BMI值就是：21.641274238227147
这位同学的身高是：165，体重是：58。所以BMI值就是：21.30394857667585
这位同学的身高是：187，体重是：82。所以BMI值就是：23.449340844748203
这位同学的身高是：140，体重是：45。所以BMI值就是：22.95918367346939


### 小范例：一颗可以客制化层数的圣诞树

In [5]:
def print_tree(level):
    width = 1
    max_width = level*2 -1
    for size in range(1, level+1):
        print(((size*2 - 1) * "*").center(max_width))
    
    trunk_hight = int(level / 5) + 1
    trunk_width = int(level / 10) + 1
    for i in range(trunk_hight):
        print(("*" * trunk_width).center(max_width))

In [ ]:
n = int(input("你想要树叶有几层高呢？"))
print_tree(n)

### 挑战题：

1. 算出`桃花庵歌`里，有几句话有提到`桃花`?
2. 算出`桃花庵歌`里，总共出现几个`花`?

In [6]:
poem_string = \
"""
桃花坞里桃花庵，桃花庵下桃花仙。桃花仙人种桃树，又摘桃花换酒钱。
酒醒只在花前坐，酒醉还来花下眠。半醉半醒日复日，花落花开年复年。
但愿老死花酒间，不愿鞠躬车马前。车尘马足显者事，酒盏花枝隐士缘。
若将显者比隐士，一在平地一在天。若将花酒比车马，彼何碌碌我何闲。
世人笑我太疯癫，我笑他人看不穿。不见五陵豪杰墓，无花无酒锄作田。
"""

### 第一题：怎么样打印出正确的 count 呢？

In [7]:
import re

count = 0 
sentence_list = re.split('，|。',poem_string)
for sentence in sentence_list:
    if '桃花' in sentence:
        count += 1
        print(sentence.strip())
        
print()
print(f'原来一共有{count}句提到桃花呢！')

桃花坞里桃花庵
桃花庵下桃花仙
桃花仙人种桃树
又摘桃花换酒钱

原来一共有4句提到桃花呢！


### 第二题：留下空白，挑战看看了！

In [ ]:
for word in poem_string:
    __ ## 试试看吧！

### 使用 Python `dictionary` 型态，做到更细部的字数计算

In [8]:
poem_string

'\n桃花坞里桃花庵，桃花庵下桃花仙。桃花仙人种桃树，又摘桃花换酒钱。\n酒醒只在花前坐，酒醉还来花下眠。半醉半醒日复日，花落花开年复年。\n但愿老死花酒间，不愿鞠躬车马前。车尘马足显者事，酒盏花枝隐士缘。\n若将显者比隐士，一在平地一在天。若将花酒比车马，彼何碌碌我何闲。\n世人笑我太疯癫，我笑他人看不穿。不见五陵豪杰墓，无花无酒锄作田。\n'

In [9]:
import operator
poem_string = poem_string.replace('。\n', '').strip()


word_count = {}
for word in poem_string:
    if word not in {'，', '。', ' '}:
        if word not in word_count:
            word_count[word] = 1
        else:
            word_count[word] += 1

print(f'字典里共有：{len(word_count)} 个字。')
print(f'印出最高频的5个字：\n')
sorted_list = sorted(word_count.items(), key=operator.itemgetter(1), reverse=True)
for i in range(5):
    print(f'{sorted_list[i][0]} 出现了 {sorted_list[i][1]} 次')

字典里共有：80 个字。
印出最高频的5个字：

花 出现了 14 次
桃 出现了 7 次
酒 出现了 7 次
人 出现了 3 次
在 出现了 3 次


## Numpy 介绍

- 建立矩阵
- 矩阵四则运算
- 矩阵进阶操作

In [10]:
import numpy as np

### 不同维度宣告方式

In [11]:
## 建立一维数组
a = np.array([1, 2, 3, 4])
print(f'a 矩阵的维度是：{a.shape}')

## 建立二维数组
b = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(f'b 矩阵的维度是：{b.shape}')

## 建立三维数组
c = np.array([[(1, 2, 3, 4), (5, 6, 7, 8)], 
             [(1, 2, 3, 4), (5, 6, 7, 8)]])
print(f'c 矩阵的维度是：{c.shape}')

a 矩阵的维度是：(4,)
b 矩阵的维度是：(2, 4)
c 矩阵的维度是：(2, 2, 4)


### 矩阵四维运算

In [12]:
a = np.array([1, 4, 9])
b = np.array([2, 4, 6])

print(a + b)
print(a * b)
print(np.sqrt(a))
print(a == b)

[ 3  8 15]
[ 2 16 54]
[1. 2. 3.]
[False  True False]


> 在 numpy 的世界， for 循环是很少出现的，不需要循序对矩阵的每个元素一一做运算，直接套用全部即可！

### 请问这个矩阵内，如果要把奇数全部加总起来，你会怎么做呢？

In [13]:
a_arr = np.array(
    [
        [[1, 4, 9, 16],[2, 7, 8, 13],[6, 5, 7, 12]],
        [[2, 5, 10, 17],[3, 8, 9, 14],[7, 6, 8, 13]],
        [[1, 4, 9, 16],[2, 7, 8, 13],[6, 5, 7, 12]],
        [[2, 5, 10, 17],[3, 8, 9, 14],[7, 6, 8, 13]]
    ])


In [14]:
## 一行搞定！

sum(a_arr[a_arr % 2 != 0])

192